using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class StarTransactionType : Object
        {
            /// <summary>
            /// The transaction is a sale of an upgraded gift; for regular users only
            /// </summary>
            public class StarTransactionTypeUpgradedGiftSale : StarTransactionType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "starTransactionTypeUpgradedGiftSale";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Identifier of the user that bought the gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public long UserId { get; set; }

                /// <summary>
                /// The gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("gift")]
                public UpgradedGift Gift { get; set; }

                /// <summary>
                /// Information about commission received by Telegram from the transaction
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("affiliate")]
                public AffiliateInfo Affiliate { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd