using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Sends an upgraded gift that is available for resale to another user or channel chat; gifts already owned by the current user
        /// must be transferred using transferGift and can't be passed to the method
        /// </summary>
        public class SendResoldGift : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "sendResoldGift";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Name of the upgraded gift to send
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("gift_name")]
            public string GiftName { get; set; }

            /// <summary>
            /// Identifier of the user or the channel chat that will receive the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("owner_id")]
            public MessageSender OwnerId { get; set; }

            /// <summary>
            /// The amount of Telegram Stars required to pay for the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("star_count")]
            public long StarCount { get; set; }
        }

        /// <summary>
        /// Sends an upgraded gift that is available for resale to another user or channel chat; gifts already owned by the current user
        /// must be transferred using transferGift and can't be passed to the method
        /// </summary>
        public static Task<Ok> SendResoldGiftAsync(
            this Client client, string giftName = default, MessageSender ownerId = default, long starCount = default)
        {
            return client.ExecuteAsync(new SendResoldGift
            {
                GiftName = giftName, OwnerId = ownerId, StarCount = starCount
            });
        }
    }
}
// REUSE-IgnoreEnd